# Generated by Django 5.2.1 on 2025-11-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی (مثلاً Backend)')),
                ('icon_class', models.CharField(max_length=50, verbose_name='کلاس آیکون (مثلاً faServer)')),
                ('color_code', models.CharField(default='#0077B6', max_length=7, verbose_name='کد رنگ هگز')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مهارت',
                'verbose_name_plural': 'دسته\u200cبندی مهارت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت (مثلاً Python)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
