# Generated by Django 5.2.1 on 2025-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order'], 'verbose_name': 'دسته\u200cبندی مهارت', 'verbose_name_plural': 'دسته\u200cبندی مهارت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='icon_name',
            field=models.CharField(default=1, max_length=50, verbose_name='نام آیکون (مثل faServer)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='order',
            field=models.IntegerField(default=100, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='color_code',
            field=models.CharField(default='#0077B6', max_length=7, verbose_name='رنگ اصلی'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی'),
        ),
    ]
