# Generated by Django 5.2.1 on 2025-11-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=200, verbose_name='عنوان انگلیسی')),
                ('short_desc_fa', models.TextField(verbose_name='توضیح کوتاه فارسی')),
                ('short_desc_en', models.TextField(verbose_name='توضیح کوتاه انگلیسی')),
                ('long_desc_fa', models.TextField(verbose_name='توضیح کامل فارسی')),
                ('long_desc_en', models.TextField(verbose_name='توضیح کامل انگلیسی')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='تصویر پروژه')),
                ('technologies', models.CharField(help_text='تکنولوژی\u200cها را با ویرگول جدا کنید. مثال: React, Django, SQL', max_length=500, verbose_name='تکنولوژی\u200cها')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک پروژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
